[package]
name = "seq_stats"
version = "0.1.0"
edition = "2021"

[dependencies]
bio = "2.2.0"
clap = { version = "4.5.34", features = ["derive"] }
flate2 = "1.1.0"
serde = "1.0.219"
serde_json = "1.0.140"
